server:
  port: 17071
#spring:
#  datasource:
#    url: jdbc:mysql://10.8.1.84:3306/herocheer_instructor?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: XZty#107110
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.8.1.84:3306/herocheer_instructor?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: XZty#107110
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      filter:
        stat:
          db-type: mysql
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5
        wall:
          config:
            delete-allow: true
            drop-table-allow: false
            multi-statement-allow: true
          db-type: mysql
          enabled: true
      filters: stat,wall #'wall'用于防火墙
      initial-size: 5
      max-active: 30
      max-pool-prepared-statement-per-connection-size: 50
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      stat-view-servlet:
        allow: '' #IP白名单(没有配置或者为空，则允许所有访问)
        deny: '' #IP黑名单 (存在共同时，deny优先于allow)
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: SELECT 1 FROM DUAL
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*

  redis:
    host: 192.168.147.134
    database: 1
    port: 6379
    password: xz107110
    timeout: 5000ms
file:
  upload:
    savePath: /root/dataExt/instructor/instructor-file/
    visitPath: https://ijs.sports.xm.gov.cn/instructor-file/
swagger:
  title: 社会指导员api文档
  description: 社会指导员api文档
  version: 1.0.0
  termsOfServiceUrl: https://ijs.sports.xm.gov.cn/instructor-server/
  license:
  licenseUrl:
  basePackage: com.herocheer.instructor.controller
  host: ijs.sports.xm.gov.cn/instructor-server
  enable: true #是否开始swagger
  contact:
    name: chenwf
    url: https://ijs.sports.xm.gov.cn/instructor-server/
    email: 349830964@qq.com

#i厦门
ixm:
  url: https://www.ixiamen.org.cn
  appName: XXCDSSFWGLXT
  secret: g8y&9X6TLMUKoLd
  redirectUrl: https://wechat.ixiamen.org.cn/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#微信公众号配置(I健身（prod）)
wechat:
  appid: wxde3b17e5dc138e40
  secret: e100c92f71d23863d1e563339714356b
  token: ijstoken001
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

#i健身保险
ijs:
  baseUrl: http://192.168.147.133/sports/wechat/api
  templateId: XXANxtmaa0iCWAbO29h5eeh7T-QoRw95pKgVMWSBiJM
  QrCodeUrl: https://ijs.sports.xm.gov.cn/instructor/#/training/trainingDetail?id={}&type=5


#i厦门APP
ixmApp:
  client_id: f6ee09d312e248f380757fd7a6351b1d
  client_secret: a4bab1a7464f434085315b1853bcf16a
  authUrl: https://auth.ixiamen.org.cn
  restUrl: https://rest.ixiamen.org.cn

#市民卡
smk:
  clientid: xmsports
  password: XM_sport#2017
  url: https://smk.ixiamen.org.cn
  userUrl: ${smk.url}/user/query-token/full
  timestampUrl: ${smk.url}/basic/timestamp #系统对时
  qrcodeGenerateUrl: ${smk.url}/qrcode/generate/303 #二维码生成
  qrcodeCheckUrl: ${smk.url}/qrcode/check #二维码识别
courier:
  station:
    url: http://ijs.sports.xm.gov.cn/instructor/#/equipment/equipmentBorrow?id={}&type=1