server:
  port: 17071
spring:
  datasource:
    url: jdbc:mysql://10.8.1.84:3306/herocheer_instructor?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: XZty#107110
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.147.134
    database: 1
    port: 6379
    password: xz107110
    timeout: 5000ms
file:
  upload:
    savePath: /root/dataExt/instructor/instructor-file/
    visitPath: https://ijs.sports.xm.gov.cn/instructor-file/
swagger:
  title: 社会指导员api文档
  description: 社会指导员api文档
  version: 1.0.0
  termsOfServiceUrl: https://ijs.sports.xm.gov.cn/instructor-server/
  license:
  licenseUrl:
  basePackage: com.herocheer.instructor.controller
  host: ijs.sports.xm.gov.cn/instructor-server
  enable: true #是否开始swagger
  contact:
    name: chenwf
    url: https://ijs.sports.xm.gov.cn/instructor-server/
    email: 349830964@qq.com

#i厦门
ixm:
  url: https://www.ixiamen.org.cn
  appName: XXCDSSFWGLXT
  secret: g8y&9X6TLMUKoLd
  redirectUrl: https://wechat.ixiamen.org.cn/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#微信公众号配置(I健身（prod）)
wechat:
  appid: wxde3b17e5dc138e40
  secret: e100c92f71d23863d1e563339714356b
  token: ijstoken001
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

#i健身保险
ijs:
  baseUrl: http://192.168.147.133/sports/wechat/api
  templateId: 2b8LbGUFPSCgLvbUyjaJ7HggjBh4Uc6dmp8-zBEQERI