server:
  port: 17071
spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/herocheer_instructor?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.36.171.139
    database: 4
    port: 6379
    password:
    timeout: 5000ms
