server:
  port: 17071
spring:
  profiles:
    active: dev
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
swagger:
  title: 社会指导员api文档
  description: 社会指导员api文档
  version: 1.0.0
  termsOfServiceUrl: http://localhost:18081/
  license:
  licenseUrl:
  basePackage: com.herocheer.instructor.controller
  enable: true #是否开始swagger
  contact:
    name: chenwf
    url: http://localhost:18081/
    email: 349830964@qq.com
file:
  upload:
    savePath: D:/images/
    visitPath: D:/images/
wechat:
  appId: wx5e3449374c04489c
  appScret: 82fdb32c5c4c461481545c42b93ffc46


