server:
  port: 17071
spring:
  profiles:
    active: dev
  servlet: # 设置上传文件的大小
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 10MB
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
swagger:
  title: 社会指导员api文档
  description: 社会指导员api文档
  version: 1.0.0
  termsOfServiceUrl: http://localhost:18081/
  license:
  licenseUrl:
  basePackage: com.herocheer.instructor.controller
  enable: true #是否开始swagger
  contact:
    name: chenwf
    url: http://localhost:18081/
    email: 349830964@qq.com
file:
  upload:
    savePath: D:/images/
    visitPath: D:/images/

wechat_xxkj:
  appId: wx5e3449374c04489c
  appScret: 82fdb32c5c4c461481545c42b93ffc46

#i厦门
#ixm:
#  url: https://www.ixiamen.org.cn
#  appName: XXCDSSFWGLXT
#  secret: g8y&9X6TLMUKoLd
#  redirectUrl: https://wechat.ixiamen.org.cn/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
#  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
#  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#测试i厦门
ixm:
  url: https://test.ixiamen.org.cn
  appName: XXCDSSFWGLXT
  secret: g8y&9X6TLMUKoLd
  redirectUrl: ${ixm.url}/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#微信公众号配置
wechat:
  appid: wx5e3449374c04489c
  secret: 82fdb32c5c4c461481545c42b93ffc46
  token: ijstoken001
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

