server:
  port: 6004
spring:
  profiles:
    active: dev
  servlet: # 设置上传文件的大小
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 10MB
  task:
    execution:
      pool:
        # 最大线程数
        max-size: 10
        # 核心线程数
        core-size: 10
        # 存活时间
        keep-alive: 10s
        # 队列大小
        queue-capacity: 100
        # 是否允许核心线程超时
        allow-core-thread-timeout: true
      # 线程名称前缀
      thread-name-prefix: instructor-async-task-
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
swagger:
  title: 社会指导员api文档
  description: 社会指导员api文档
  version: 1.0.0
  termsOfServiceUrl: http://localhost:18081/
  license:
  licenseUrl:
  basePackage: com.herocheer.instructor.controller
  host:
  enable: true #是否开始swagger
  contact:
    name: chenwf
    url: http://localhost:18081/
    email: 349830964@qq.com
file:
  upload:
    savePath: D:/images/
    visitPath: D:/images/

#i厦门
#ixm:
#  url: https://www.ixiamen.org.cn
#  appName: XXCDSSFWGLXT
#  secret: g8y&9X6TLMUKoLd
#  redirectUrl: https://wechat.ixiamen.org.cn/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
#  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
#  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#i健身保险(test)
ijs:
  baseUrl: http://tycd.herocheer.com/sports/wechat/api
  templateId: J1XrAfrpV-SfeeKuLEX91e6MNIPy72zoYX6iRhJLrcc
  QrCodeUrl: http://tycd.herocheer.com/instructor/#/training/trainingDetail?id={}&type=5


#测试i厦门
ixm:
  url: https://test.ixiamen.org.cn
  appName: XXCDSSFWGLXT
  secret: g8y&9X6TLMUKoLd
  redirectUrl: ${ixm.url}/ixm-wechat/wxchat/api/proxy.jhtml?coAppName=${ixm.appName}&state=redirect&sUrl=%s&createTime=%s
  userUrl: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=findUserBySSOID
  userLogOut: ${ixm.url}/ids/service?idsServiceType=httpssoservice&serviceName=logout

#微信公众号配置(创智云校园)
wechat:
  appid: wxf6c55bc2f36ca69b
  secret: 0f7eceb412da0a68b533ad303774da89
  token: ijstoken001
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s


#微信公众号配置(熙信科技)
#wechat:
#  appid: wx5e3449374c04489c
#  secret: 82fdb32c5c4c461481545c42b93ffc46
#  token: ijstoken001
#  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
#  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
#  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
#  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

#微信公众号配置(I健身（prod）)
#wechat:
#  appid: wxde3b17e5dc138e40
#  secret: e100c92f71d23863d1e563339714356b
#  token: ijstoken001
#  tokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
#  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code
#  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi
#  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=%s

#i厦门APP（测试环境）
ixmApp:
  client_id: f6ee09d312e248f380757fd7a6351b1d
  client_secret: a4bab1a7464f434085315b1853bcf16a
  authUrl: https://auth-test.ixiamen.org.cn
  restUrl: https://rest-test.ixiamen.org.cn

#市民卡(测试环境)
smk:
  clientid: sports
  password: sports@2019
  url:  http://218.5.69.218:9088
  userUrl: ${smk.url}/user/query-token/full
  timestampUrl: ${smk.url}/basic/timestamp #系统对时
  qrcodeGenerateUrl: ${smk.url}/qrcode/generate/303 #二维码生成
  qrcodeCheckUrl: ${smk.url}/qrcode/check #二维码识别

courier:
  station:
    url: http://tycd.herocheer.com/instructor/#/equipment/equipmentBorrow?id={}&type=2