server:
  port: 17071
spring:
  datasource:
    url: jdbc:mysql://192.168.100.10:3306/herocheer_instructor?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.100.10
    database: 4
    port: 6379
    password:
    timeout: 5000ms
file:
  ftp:
    host: 192.168.100.10
    port: 21
    username: Administrator
    password: xz107110%
    basePath: /instructor
    visitPath: D:/ftpserver #访问地址前缀  linux http://localhost:1111/xxx/xx/xx.png

